# Generated by Django 4.1.5 on 2023-03-17 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='profile_pics',
            field=models.FileField(default='default.png', null=True, upload_to='profile_pics/'),
        ),
    ]
