# Generated by Django 4.1.5 on 2023-03-17 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_account_profile_pics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='profile_pics',
            field=models.FileField(default='default.jpg', null=True, upload_to='profile_pics/'),
        ),
    ]
