# Generated by Django 4.1.5 on 2023-03-21 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_account_profile_pics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='profile_pics',
            field=models.FileField(default='profile_pics/default.jpg', null=True, upload_to='profile_pics/'),
        ),
    ]
