# Generated by Django 4.1.5 on 2023-03-22 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_account_profile_pics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='authority',
            field=models.CharField(blank=True, choices=[('ตำรวจจราจร', 'จร'), ('ตํารวจส่วนท้องถิ่น', 'ตท'), ('กรมทางหลวง+', 'ทล')], max_length=30),
        ),
    ]
