# Generated by Django 3.2.18 on 2023-04-23 16:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(blank=True, max_length=1000)),
                ('name', models.CharField(blank=True, max_length=1000)),
                ('location', models.CharField(blank=True, max_length=1000)),
                ('status', models.CharField(blank=True, max_length=100)),
                ('authority_need', models.CharField(blank=True, max_length=1000)),
                ('description', models.CharField(blank=True, max_length=1000)),
                ('date_collect', models.DateField(default=datetime.date.today)),
                ('date_modify', models.DateTimeField(default=datetime.datetime.now)),
                ('date_upload', models.DateTimeField(default=datetime.datetime.now)),
                ('video', models.FileField(null=True, upload_to='videos/', verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(blank=True, max_length=1000)),
                ('speed', models.FloatField(blank=True)),
                ('direection', models.CharField(blank=True, max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to=None)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='Loop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loop_name', models.CharField(blank=True, max_length=1000)),
                ('width', models.FloatField(default=1)),
                ('height', models.FloatField(default=1)),
                ('angle', models.FloatField(default=1)),
                ('color', models.CharField(default='black', max_length=1000)),
                ('x_axis', models.FloatField(default=1)),
                ('y_axis', models.FloatField(default=1)),
                ('task', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='task.task')),
            ],
        ),
    ]
