# Generated by Django 3.2.18 on 2023-05-13 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0008_remove_task_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Result',
        ),
        migrations.DeleteModel(
            name='Vehicle',
        ),
    ]
