# Generated by Django 3.2.18 on 2023-05-13 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0009_auto_20230513_2356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loop',
            name='angle',
        ),
        migrations.RemoveField(
            model_name='loop',
            name='color',
        ),
        migrations.RemoveField(
            model_name='loop',
            name='height',
        ),
        migrations.RemoveField(
            model_name='loop',
            name='width',
        ),
        migrations.RemoveField(
            model_name='loop',
            name='x_axis',
        ),
        migrations.RemoveField(
            model_name='loop',
            name='y_axis',
        ),
        migrations.AddField(
            model_name='loop',
            name='orientation',
            field=models.CharField(choices=[('cw', 'clockwise'), ('ctcw', 'counterclockwise')], default='cw', max_length=100),
        ),
        migrations.AddField(
            model_name='loop',
            name='summary_location_x',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='loop',
            name='summary_location_y',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='loop',
            name='x1',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='loop',
            name='x2',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='loop',
            name='x3',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='loop',
            name='x4',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='loop',
            name='y1',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='loop',
            name='y2',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='loop',
            name='y3',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='loop',
            name='y4',
            field=models.FloatField(null=True),
        ),
    ]
