# Generated by Django 3.2.18 on 2023-05-13 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0010_auto_20230514_0542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loop',
            name='summary_location_x',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='loop',
            name='summary_location_y',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='loop',
            name='x1',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='loop',
            name='x2',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='loop',
            name='x3',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='loop',
            name='x4',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='loop',
            name='y1',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='loop',
            name='y2',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='loop',
            name='y3',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='loop',
            name='y4',
            field=models.IntegerField(null=True),
        ),
    ]
