# Generated by Django 4.1.7 on 2023-03-02 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VDO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loop', models.FileField(upload_to='vdo')),
                ('vdo', models.FileField(upload_to='vdo')),
            ],
        ),
    ]
