# Generated by Django 4.1.7 on 2023-03-03 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_vdo_vdo'),
    ]

    operations = [
        migrations.AddField(
            model_name='vdo',
            name='vdo',
            field=models.FileField(default=5, upload_to='vdo/%Y/%m/%d/%H/%M'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vdo',
            name='loop',
            field=models.FileField(upload_to='vdo/%Y/%m/%d/%H/%M'),
        ),
    ]
